### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [kaji-ryuya/beppu_app#31]
ご提出ありがとうございます。
以下の観点からレビューを行います。

1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

---

#### 1について
不足している箇所はありますが、温泉を探す機能は実装できていますね。

#### 2について
いくつか気になった箇所があったのでRubocop等のコードチェックツールを使って修正しておきましょう。JSもビューファイルに直書きされている箇所が散見されたので、可能ならRailsのレールに乗った方法で管理＆機能が反映されるようにしましょう。

#### 3について
やや「CRUD+αのアプリ」といった印象＆データベースのテーブル数が少ない受けました。位置情報をGoogle Map上に表示させている部分・ステップ入力部分は１つのアピールポイントになるかと思います。

#### 4について
全体的には特に問題無さそうに感じました。ただトップページの温泉の詳細が見れるのかと思いましたが、文字列だけだったことに戸惑いは感じました。

#### その他
今後追加したいサービスに加えて、以下の機能も取り入れられると技術アピールできるポイントが増えるかと思いますのでご検討ください。

レコメンド
概要：投稿されたまたは事前に用意されたコンテンツと類似したコンテンツを推奨する機能をレコメンドと呼びます。代表的なアルゴリズムとして、協調フィルタリングとコンテンツフィルタリングがあります。協調フィルタリングは、ユーザの行動や嗜好データを元に類似度を算出し、コンテンツベースフィルタリングは、コンテンツの数値化された特徴や評価を元に類似度を算出します。
使用技術・ライブラリ：
- Amazon Personalize
  - https://docs.aws.amazon.com/ja_jp/personalize/latest/dg/what-is-personalize.html
  - AWSが提供する機械学習の知識がなくても、個々のユーザー向けにリコメンデーションをリアルタイムで提供できるサービスです。
- GCP Recommendations AI
  - https://cloud.google.com/recommendations?hl=ja
  - Recommendations AIは、Google Cloud Platformが提供するレコメンドエンジンであり、Googleの機械学習アルゴリズムを利用しています。
- アルゴリズム
  - 協調フィルタリングやコンテンツベースフィルタリングは、一般的にアルゴリズムが公開されているので、RubyやPythonで独自に実装することも可能です。

**Comment by Tsuchiya2** [comment]
--- 質問 ---
本リリースまでに実装予定の機能とリリース予定日をお答えください。

**Comment by kaji-ryuya** [comment]
レビューありがとうございます！
教えていただいたレコメンドの技術を調べたいので、リリース予定日は追ってご連絡いたします。
実装予定機能について、
- ブックマーク機能
- ブックマーク数でランキング化
- 質問の枝分かれの追加
- 温泉情報の追加（データが少なければ、大分市や湯布院も視野）

3つ質問があるのですが、
1. 「3について」のステップ入力部分というのは、質問から温泉を探す機能のことでしょうか。
2. 「4について」の「トップページの温泉の詳細が見れるのかと思いました」はリストでそのエリアを検索した状態のようなリンクでしょうか。それとも、各エリアの詳しい説明のような感じでしょうか。
3. 「教えていただいたレコメンド機能について」 現在の質問から温泉を探す機能に加えて、どの温泉の詳細ページに多く訪れたかを年代や性別から探し、それを表示するような機能のイメージなのですが、相違ないでしょうか。

お忙しいとは存じますが、ご回答頂きたく存じます。よろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
以下質問への回答になります。

1：そうですね。その部分になります。
2：共有いただいているURLに表示されるページの下部にある温泉ですね。
３：ユーザーの傾向からそのユーザーに適したレコメンドは難しいかもしれませんね。ユーザー登録を実装しない場合、ブックマークも難しいと思いますが、どのようにするのかよくよく考えてみてください。（開発者は貴方ですのでどのようにするのかはお任せします）

---

本リリースへ実装する機能・日時ありがとうございます。
引き続き開発頑張ってください。
