### ISSUE TITLE
本番環境でのパスワードリセットのメール送信を行いたい

### ISSUE THREAD

**Issue by kaji-ryuya** [kaji-ryuya/beppu_app#52]
- 質問内容・実現したいこと

本番環境でのパスワードリセット機能のメールをgmailを利用して送信できるようにしたいです。
パスワードリセットにはsorceryのmoduleを使用しています。
- 現在発生している問題、エラーメッセージ

パスワードリセット機能にて、メールが送信されない状態です。
herokuのlogを見ると下記のエラーが発生しています。
```
Net::SMTPAuthenticationError (530-5.7.0 Authentication Required. Learn more at ):
```
- どの処理までうまく動いているのか

開発環境でletter_openerを使用してのメール送信はできています。
- 該当のソースコード

gmailのパスワードは2段階認証で取得しています。
```
# config/environments/production.rb

require "active_support/core_ext/integer/time"

Rails.application.configure do
~省略~
  config.action_mailer.perform_caching = false
  config.action_mailer.default_url_options = Settings.default_url_options.to_h
  config.action_mailer.delivery_method = :smtp
  config.action_mailer.smtp_settings = {
    address: "smtp.gmail.com",
    port: 587,
    domain: "gmail.com",
    user_name: ENV['GMAIL_ADDRESS'],
    password: ENV['GMAIL_PASS'],
    authentication: :plain,
    enable_starttls_auto: true
  }
~省略~
end
```
```
class PasswordResetsController < ApplicationController
  def new; end

  def create 
    @user = User.find_by(email: params[:email])
    @user&.deliver_reset_password_instructions!
    redirect_to login_path, success: 'パスワードリセット手順を送信しました。'
  end
~省略~
```
```
# config/settings/production.rb

default_url_options:
  protocol: 'https'
  host: 'www.beppu-app.com'
```

- エラーから考えられる原因

エラーから、SMTP認証が正しく行われなかったことが読み取れます。
しかし、環境変数のgmailアドレス（user_name）、2段階認証のアプリパスワード（password）は間違いなく入れているため、見当がついていません。
- 試したこと

・Gmailの設定（2段階認証の設定）を行い、再デプロイ、herokuの再起動を行った。
・user_name, passwordを環境変数に変えた。（参考： https://qiita.com/kobayashimakoto/items/c7a96ea9f6cbc8d2da77 ）

**Comment by Tsuchiya2** [comment]
そうですね。。ローカルではできていたという前提で考えると、本番環境で以下の部分が適切な値を返すか確認してみましょう。

- Settings.default_url_options.to_h
- ENV['GMAIL_ADDRESS']
- ENV['GMAIL_PASS']

また、master.keyはローカルにはあるかと思いますが、本番環境にはセットできているかも確認してみましょう。

**Comment by kaji-ryuya** [comment]
ローカルでのproduction環境（rails c）で値を確認していました。
herokuで確認してみると、誤った値が登録されていたのが原因でした。
ありがとうございました！
